### PR TITLE
Responsive hero card gallery YAML snippet

### PR DESCRIPTION
**Pull request by scottdurow**
This pull request introduces a new responsive hero card gallery for Power Apps. The changes include documentation, a sample JSON file, and a YAML snippet to define the gallery structure.

### CODE REVIEW

**Comment by scottdurow** [comment]
@aprildunnam Could you review please!

**Comment by aprildunnam** [comment]
@scottdurow for some reason whenever I paste this I get two errors related to the height of objects.  It's like it isn't recognizing the cCards and txtCardSubtitle but if I manually remove and re-type those properties it recognizes them and works.  Not sure if there's any way around this?

**Comment by scottdurow** [comment]
Yes I get that too (I had made a note about it in step 5 of the instructions). It seems to be a bug in Power Apps studio which looks like it's fixed in the preview version. The issue happens if you just copy and paste normally as well.

**Review by Laskewitz — APPROVED** [review]
Thanks for the contribution! Merging now!

**Pull request merged**
