### PR TITLE
Glass Effect Template

### PR DESCRIPTION
**Pull request by leorrusso**
This snippet showcases a full mobile screen using glass effect through the HTML component

screen-glass

### CODE REVIEW

**Review by Laskewitz — APPROVED** [review]
Thanks @leorrusso! Great submission - really cool snippet!

Sorry for the late processing - but I had some holiday + Ignite in between! 😁

**Comment by leorrusso** [comment]
@Laskewitz no worries! Thanks!!

**Comment by leorrusso** [comment]
> Thanks @leorrusso! Great submission - really cool snippet!
> 
> Sorry for the late processing - but I had some holiday + Ignite in between! 😁

@Laskewitz no worries, thanks!

**Comment by PopWarner** [comment]
🎉✨ Woohoo! ✨🎉

Thank you @leorrusso for your awesome contribution to the community with this merged PR! 🚀 You've earned a Credly badge through the Microsoft 365 & Power Platform Recognition Program. 🏅 To receive your badge, please take a moment to opt in to the program. You can learn more and sign up here: https://aka.ms/community/recognition.

Can't wait to see you in the program! 🎊

Thank you,
David Warner 🧡💜

cc: @aprildunnam @Laskewitz

**Comment by leorrusso** [comment]
@PopWarner Woohoo!! I've joined the program, can't wait to get my badge 🔥😁

@aprildunnam @Laskewitz

**Pull request merged**
